### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by jcampbell05** [Khan/SwiftTweaks#57] opened 2016-06-08 15:57 UTC
I would love to have custom text to show information like API URL.

**Comment by ikesyo** [comment] 2016-06-08 16:51
This may be a duplicate of #14?

**Comment by bryanjclark** [comment] 2016-06-10 19:53
Yep, this is a duplicate of #14 - thanks @ikesyo and @jcampbell05!

**Closed by bryanjclark** 2016-06-10 19:53 UTC
