### ISSUE TITLE
Umbrella Header "SwiftTweaks.h" not found

### ISSUE THREAD

**Issue by TusharGarg** [Khan/SwiftTweaks#77] opened 2016-11-14 14:16 UTC
I am trying to run the example iOS project attached in the repo. While running it, I am getting the following build error: 

> Umbrella Header "SwiftTweaks.h" not found

_Xcode Version: 8.1_ 

I tried to fix it using information from this [link](http://stackoverflow.com/questions/30355133/swift-framework-umbrella-header-h-not-found) but that didn't help.

**Comment by bryanjclark** [comment] 2016-11-14 18:29
Thanks for filing the bug! This is a duplicate of #61; closing as a duplicate.

**Closed by bryanjclark** 2016-11-14 18:29 UTC

**Comment by TusharGarg** [comment] 2016-11-16 02:13
Thank you for a quick response @bryanjclark. 
My bad. I should have gone through the list of open issues first.
